[package]
name = "cash"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.5"
once_cell = "1.18.0"
signal-hook = { version = "0.3.15", features = ["extended-siginfo"] } 
termion = "2.0.1"
toml = "0.7.6"
users = "0.11.0"
